#!/bin/bash

# Audience builder sources
cp audience_builder/less/audience_builder.less ../mab/client/less/dashboard/audience_builder.less
cp audience_builder/less/animations.less ../mab/client/less/dashboard/animations.less
cp audience_builder/templates/*.thtml ../mab/client/templates/
cp audience_builder/src/models/*.coffee ../mab/client/lib/dashboard/campaigns/models/
cp audience_builder/src/views/audience_*.coffee ../mab/client/lib/dashboard/campaigns/views/

# Shared sources
cp shared/less/tooltips.less ../mab/client/less/shared/
cp shared/templates/svg-icons.thtml ../mab/client/templates/
cp shared/collections/*_audiences.coffee ../mab/client/lib/shared/collections/
cp shared/models/*_audience.coffee ../mab/client/lib/shared/models/
