var constants = [
    {"id": "AF", "label":"Afghanistan", "regionId": "APAC"},
    {"id": "BD", "label":"Bangladesh", "regionId": "APAC"},
    {"id": "BT", "label":"Bhutan", "regionId": "APAC"},
    {"id": "IN", "label":"India", "regionId": "APAC"},
    {"id": "IR", "label":"Iran", "regionId": "APAC"},
    {"id": "MV", "label":"Maldives", "regionId": "APAC"},
    {"id": "NP", "label":"Nepal", "regionId": "APAC"},
    {"id": "PK", "label":"Pakistan", "regionId": "APAC"},
    {"id": "LK", "label":"Sri Lanka", "regionId": "APAC"},
    {"id": "AU", "label":"Australia", "regionId": "APAC"},
    {"id": "NZ", "label":"New Zealand", "regionId": "APAC"},
    {"id": "NF", "label":"Norfolk Island", "regionId": "APAC"},
    {"id": "CN", "label":"China", "regionId": "APAC"},
    {"id": "HK", "label":"Hong Kong SAR China", "regionId": "APAC"},
    {"id": "MO", "label":"Macau SAR China", "regionId": "APAC"},
    {"id": "JP", "label":"Japan", "regionId": "APAC"},
    {"id": "MN", "label":"Mongolia", "regionId": "APAC"},
    {"id": "KP", "label":"North Korea", "regionId": "APAC"},
    {"id": "KR", "label":"South Korea", "regionId": "APAC"},
    {"id": "TW", "label":"Taiwan", "regionId": "APAC"},
    {"id": "FJ", "label":"Fiji", "regionId": "APAC"},
    {"id": "NC", "label":"New Caledonia", "regionId": "APAC"},
    {"id": "PG", "label":"Papua New Guinea", "regionId": "APAC"},
    {"id": "SB", "label":"Solomon Islands", "regionId": "APAC"},
    {"id": "VU", "label":"Vanuatu", "regionId": "APAC"},
    {"id": "GU", "label":"Guam", "regionId": "APAC"},
    {"id": "KI", "label":"Kiribati", "regionId": "APAC"},
    {"id": "MH", "label":"Marshall Islands", "regionId": "APAC"},
    {"id": "FM", "label":"Micronesia", "regionId": "APAC"},
    {"id": "NR", "label":"Nauru", "regionId": "APAC"},
    {"id": "MP", "label":"Northern Mariana Islands", "regionId": "APAC"},
    {"id": "PW", "label":"Palau", "regionId": "APAC"},
    {"id": "BN", "label":"Brunei", "regionId": "APAC"},
    {"id": "KH", "label":"Cambodia", "regionId": "APAC"},
    {"id": "ID", "label":"Indonesia", "regionId": "APAC"},
    {"id": "LA", "label":"Laos", "regionId": "APAC"},
    {"id": "MY", "label":"Malaysia", "regionId": "APAC"},
    {"id": "MM", "label":"Myanmar [Burma]", "regionId": "APAC"},
    {"id": "PH", "label":"Philippines", "regionId": "APAC"},
    {"id": "SG", "label":"Singapore", "regionId": "APAC"},
    {"id": "TH", "label":"Thailand", "regionId": "APAC"},
    {"id": "TL", "label":"Timor-Leste", "regionId": "APAC"},
    {"id": "VN", "label":"Vietnam", "regionId": "APAC"},
    {"id": "TJ", "label":"Tajikistan", "regionId": "EMEA"},
    {"id": "TM", "label":"Turkmenistan", "regionId": "EMEA"},
    {"id": "UZ", "label":"Uzbekistan", "regionId": "EMEA"},
    {"id": "BI", "label":"Burundi", "regionId": "EMEA"},
    {"id": "KM", "label":"Comoros", "regionId": "EMEA"},
    {"id": "DJ", "label":"Djibouti", "regionId": "EMEA"},
    {"id": "ER", "label":"Eritrea", "regionId": "EMEA"},
    {"id": "ET", "label":"Ethiopia", "regionId": "EMEA"},
    {"id": "KE", "label":"Kenya", "regionId": "EMEA"},
    {"id": "MG", "label":"Madagascar", "regionId": "EMEA"},
    {"id": "MW", "label":"Malawi", "regionId": "EMEA"},
    {"id": "MU", "label":"Mauritius", "regionId": "EMEA"},
    {"id": "YT", "label":"Mayotte", "regionId": "EMEA"},
    {"id": "MZ", "label":"Mozambique", "regionId": "EMEA"},
    {"id": "RW", "label":"Rwanda", "regionId": "EMEA"},
    {"id": "RE", "label":"Réunion", "regionId": "EMEA"},
    {"id": "SC", "label":"Seychelles", "regionId": "EMEA"},
    {"id": "SO", "label":"Somalia", "regionId": "EMEA"},
    {"id": "TZ", "label":"Tanzania", "regionId": "EMEA"},
    {"id": "UG", "label":"Uganda", "regionId": "EMEA"},
    {"id": "ZM", "label":"Zambia", "regionId": "EMEA"},
    {"id": "ZW", "label":"Zimbabwe", "regionId": "EMEA"},
    {"id": "AT", "label":"Austria", "regionId": "EMEA"},
    {"id": "BE", "label":"Belgium", "regionId": "EMEA"},
    {"id": "FR", "label":"France", "regionId": "EMEA"},
    {"id": "DE", "label":"Germany", "regionId": "EMEA"},
    {"id": "LI", "label":"Liechtenstein", "regionId": "EMEA"},
    {"id": "LU", "label":"Luxembourg", "regionId": "EMEA"},
    {"id": "MC", "label":"Monaco", "regionId": "EMEA"},
    {"id": "NL", "label":"Netherlands", "regionId": "EMEA"},
    {"id": "CH", "label":"Switzerland", "regionId": "EMEA"},
    {"id": "BH", "label":"Bahrain", "regionId": "EMEA"},
    {"id": "CY", "label":"Cyprus", "regionId": "EMEA"},
    {"id": "IQ", "label":"Iraq", "regionId": "EMEA"},
    {"id": "IL", "label":"Israel", "regionId": "EMEA"},
    {"id": "JO", "label":"Jordan", "regionId": "EMEA"},
    {"id": "KW", "label":"Kuwait", "regionId": "EMEA"},
    {"id": "LB", "label":"Lebanon", "regionId": "EMEA"},
    {"id": "OM", "label":"Oman", "regionId": "EMEA"},
    {"id": "PS", "label":"Palestinian Territories", "regionId": "EMEA"},
    {"id": "QA", "label":"Qatar", "regionId": "EMEA"},
    {"id": "SA", "label":"Saudi Arabia", "regionId": "EMEA"},
    {"id": "SY", "label":"Syria", "regionId": "EMEA"},
    {"id": "TR", "label":"Turkey", "regionId": "EMEA"},
    {"id": "AE", "label":"United Arab Emirates", "regionId": "EMEA"},
    {"id": "YE", "label":"Yemen", "regionId": "EMEA"},
    {"id": "AL", "label":"Albania", "regionId": "EMEA"},
    {"id": "AD", "label":"Andorra", "regionId": "EMEA"},
    {"id": "BA", "label":"Bosnia and Herzegovina", "regionId": "EMEA"},
    {"id": "HR", "label":"Croatia", "regionId": "EMEA"},
    {"id": "GI", "label":"Gibraltar", "regionId": "EMEA"},
    {"id": "GR", "label":"Greece", "regionId": "EMEA"},
    {"id": "IT", "label":"Italy", "regionId": "EMEA"},
    {"id": "MK", "label":"Macedonia", "regionId": "EMEA"},
    {"id": "MT", "label":"Malta", "regionId": "EMEA"},
    {"id": "ME", "label":"Montenegro", "regionId": "EMEA"},
    {"id": "PT", "label":"Portugal", "regionId": "EMEA"},
    {"id": "SM", "label":"San Marino", "regionId": "EMEA"},
    {"id": "RS", "label":"Serbia", "regionId": "EMEA"},
    {"id": "SI", "label":"Slovenia", "regionId": "EMEA"},
    {"id": "ES", "label":"Spain", "regionId": "EMEA"},
    {"id": "VA", "label":"Vatican City", "regionId": "EMEA"},
    {"id": "BJ", "label":"Benin", "regionId": "EMEA"},
    {"id": "BF", "label":"Burkina Faso", "regionId": "EMEA"},
    {"id": "CV", "label":"Cape Verde", "regionId": "EMEA"},
    {"id": "CI", "label":"Côte d’Ivoire", "regionId": "EMEA"},
    {"id": "GM", "label":"Gambia", "regionId": "EMEA"},
    {"id": "GH", "label":"Ghana", "regionId": "EMEA"},
    {"id": "GN", "label":"Guinea", "regionId": "EMEA"},
    {"id": "GW", "label":"Guinea-Bissau", "regionId": "EMEA"},
    {"id": "LR", "label":"Liberia", "regionId": "EMEA"},
    {"id": "ML", "label":"Mali", "regionId": "EMEA"},
    {"id": "MR", "label":"Mauritania", "regionId": "EMEA"},
    {"id": "NE", "label":"Niger", "regionId": "EMEA"},
    {"id": "NG", "label":"Nigeria", "regionId": "EMEA"},
    {"id": "SH", "label":"Saint Helena", "regionId": "EMEA"},
    {"id": "SN", "label":"Senegal", "regionId": "EMEA"},
    {"id": "SL", "label":"Sierra Leone", "regionId": "EMEA"},
    {"id": "TG", "label":"Togo", "regionId": "EMEA"},
    {"id": "BW", "label":"Botswana", "regionId": "EMEA"},
    {"id": "LS", "label":"Lesotho", "regionId": "EMEA"},
    {"id": "NA", "label":"Namibia", "regionId": "EMEA"},
    {"id": "ZA", "label":"South Africa", "regionId": "EMEA"},
    {"id": "SZ", "label":"Swaziland", "regionId": "EMEA"},
    {"id": "DK", "label":"Denmark", "regionId": "EMEA"},
    {"id": "EE", "label":"Estonia", "regionId": "EMEA"},
    {"id": "FO", "label":"Faroe Islands", "regionId": "EMEA"},
    {"id": "FI", "label":"Finland", "regionId": "EMEA"},
    {"id": "IS", "label":"Iceland", "regionId": "EMEA"},
    {"id": "IE", "label":"Ireland", "regionId": "EMEA"},
    {"id": "IM", "label":"Isle of Man", "regionId": "EMEA"},
    {"id": "LV", "label":"Latvia", "regionId": "EMEA"},
    {"id": "LT", "label":"Lithuania", "regionId": "EMEA"},
    {"id": "NO", "label":"Norway", "regionId": "EMEA"},
    {"id": "SJ", "label":"Svalbard and Jan Mayen", "regionId": "EMEA"},
    {"id": "SE", "label":"Sweden", "regionId": "EMEA"},
    {"id": "GB", "label":"United Kingdom", "regionId": "EMEA"},
    {"id": "BY", "label":"Belarus", "regionId": "EMEA"},
    {"id": "BG", "label":"Bulgaria", "regionId": "EMEA"},
    {"id": "CZ", "label":"Czech Republic", "regionId": "EMEA"},
    {"id": "HU", "label":"Hungary", "regionId": "EMEA"},
    {"id": "MD", "label":"Moldova", "regionId": "EMEA"},
    {"id": "PL", "label":"Poland", "regionId": "EMEA"},
    {"id": "RO", "label":"Romania", "regionId": "EMEA"},
    {"id": "RU", "label":"Russia", "regionId": "EMEA"},
    {"id": "SK", "label":"Slovakia", "regionId": "EMEA"},
    {"id": "AM", "label":"Armenia", "regionId": "EMEA"},
    {"id": "AZ", "label":"Azerbaijan", "regionId": "EMEA"},
    {"id": "GE", "label":"Georgia", "regionId": "EMEA"},
    {"id": "KZ", "label":"Kazakhstan", "regionId": "EMEA"},
    {"id": "KG", "label":"Kyrgyzstan", "regionId": "EMEA"},
    {"id": "UA", "label":"Ukraine", "regionId": "EMEA"},
    {"id": "DZ", "label":"Algeria", "regionId": "EMEA"},
    {"id": "EG", "label":"Egypt", "regionId": "EMEA"},
    {"id": "LY", "label":"Libya", "regionId": "EMEA"},
    {"id": "MA", "label":"Morocco", "regionId": "EMEA"},
    {"id": "SD", "label":"Sudan", "regionId": "EMEA"},
    {"id": "TN", "label":"Tunisia", "regionId": "EMEA"},
    {"id": "EH", "label":"Western Sahara", "regionId": "EMEA"},
    {"id": "AO", "label":"Angola", "regionId": "EMEA"},
    {"id": "CM", "label":"Cameroon", "regionId": "EMEA"},
    {"id": "CF", "label":"Central African Republic", "regionId": "EMEA"},
    {"id": "TD", "label":"Chad", "regionId": "EMEA"},
    {"id": "CG", "label":"Congo - Brazzaville", "regionId": "EMEA"},
    {"id": "CD", "label":"Congo - Kinshasa", "regionId": "EMEA"},
    {"id": "GQ", "label":"Equatorial Guinea", "regionId": "EMEA"},
    {"id": "GA", "label":"Gabon", "regionId": "EMEA"},
    {"id": "ST", "label":"São Tomé and Príncipe", "regionId": "EMEA"},
    {"id": "AI", "label":"Anguilla", "regionId": "NA"},
    {"id": "AG", "label":"Antigua and Barbuda", "regionId": "NA"},
    {"id": "AW", "label":"Aruba", "regionId": "NA"},
    {"id": "BS", "label":"Bahamas", "regionId": "NA"},
    {"id": "BB", "label":"Barbados", "regionId": "NA"},
    {"id": "VG", "label":"British Virgin Islands", "regionId": "NA"},
    {"id": "KY", "label":"Cayman Islands", "regionId": "NA"},
    {"id": "CU", "label":"Cuba", "regionId": "NA"},
    {"id": "DM", "label":"Dominica", "regionId": "NA"},
    {"id": "DO", "label":"Dominican Republic", "regionId": "NA"},
    {"id": "GD", "label":"Grenada", "regionId": "NA"},
    {"id": "GP", "label":"Guadeloupe", "regionId": "NA"},
    {"id": "HT", "label":"Haiti", "regionId": "NA"},
    {"id": "JM", "label":"Jamaica", "regionId": "NA"},
    {"id": "MQ", "label":"Martinique", "regionId": "NA"},
    {"id": "MS", "label":"Montserrat", "regionId": "NA"},
    {"id": "AN", "label":"Netherlands Antilles", "regionId": "NA"},
    {"id": "PR", "label":"Puerto Rico", "regionId": "NA"},
    {"id": "BL", "label":"Saint Barthélemy", "regionId": "NA"},
    {"id": "KN", "label":"Saint Kitts and Nevis", "regionId": "NA"},
    {"id": "LC", "label":"Saint Lucia", "regionId": "NA"},
    {"id": "VC", "label":"Saint Vincent and the Grenadines", "regionId": "NA"},
    {"id": "TT", "label":"Trinidad and Tobago", "regionId": "NA"},
    {"id": "TC", "label":"Turks and Caicos Islands", "regionId": "NA"},
    {"id": "VI", "label":"U.S. Virgin Islands", "regionId": "NA"},
    {"id": "BZ", "label":"Belize", "regionId": "NA"},
    {"id": "CR", "label":"Costa Rica", "regionId": "NA"},
    {"id": "SV", "label":"El Salvador", "regionId": "NA"},
    {"id": "GT", "label":"Guatemala", "regionId": "NA"},
    {"id": "HN", "label":"Honduras", "regionId": "NA"},
    {"id": "MX", "label":"Mexico", "regionId": "NA"},
    {"id": "NI", "label":"Nicaragua", "regionId": "NA"},
    {"id": "PA", "label":"Panama", "regionId": "NA"},
    {"id": "BM", "label":"Bermuda", "regionId": "NA"},
    {"id": "CA", "label":"Canada", "regionId": "NA"},
    {"id": "GL", "label":"Greenland", "regionId": "NA"},
    {"id": "PM", "label":"Saint Pierre and Miquelon", "regionId": "NA"},
    {"id": "US", "label":"United States", "regionId": "NA"},
    {"id": "AR", "label":"Argentina", "regionId": "SA"},
    {"id": "BO", "label":"Bolivia", "regionId": "SA"},
    {"id": "BR", "label":"Brazil", "regionId": "SA"},
    {"id": "CL", "label":"Chile", "regionId": "SA"},
    {"id": "CO", "label":"Colombia", "regionId": "SA"},
    {"id": "EC", "label":"Ecuador", "regionId": "SA"},
    {"id": "FK", "label":"Falkland Islands", "regionId": "SA"},
    {"id": "GF", "label":"French Guiana", "regionId": "SA"},
    {"id": "GY", "label":"Guyana", "regionId": "SA"},
    {"id": "PY", "label":"Paraguay", "regionId": "SA"},
    {"id": "PE", "label":"Peru", "regionId": "SA"},
    {"id": "SR", "label":"Surilabel", "regionId": "SA"},
    {"id": "UY", "label":"Uruguay", "regionId": "SA"},
    {"id": "VE", "label":"Venezuela", "regionId": "SA"},
    {"id": "EC", "label":"Ecuador", "regionId": "SA"},
    {"id": "AS", "label":"American Samoa", "regionId": "APAC"},
    {"id": "CK", "label":"Cook Islands", "regionId": "APAC"},
    {"id": "PF", "label":"French Polynesia", "regionId": "APAC"},
    {"id": "NU", "label":"Niue", "regionId": "APAC"},
    {"id": "PN", "label":"Pitcairn Islands", "regionId": "APAC"},
    {"id": "WS", "label":"Samoa", "regionId": "APAC"},
    {"id": "TK", "label":"Tokelau", "regionId": "APAC"},
    {"id": "TO", "label":"Tonga", "regionId": "APAC"},
    {"id": "TV", "label":"Tuvalu", "regionId": "APAC"},
    {"id": "WF", "label":"Wallis and Futuna", "regionId": "APAC"}
];

Object.keys(constants).forEach(function(key) {
    function ucfirst(s) {
        return s.charAt(0).toUpperCase() + s.slice(1);
    }
    
    constants['get'+ucfirst(key).slice(0, -1)+'ById'] = function(id, nullOk) {
        var collection = constants[key];
        for (var i = 0; i < collection.length; i++) {
            var elem = collection[i];
            if (elem.id === id)
                return elem;
        }
        
        if (nullOk)
            return null;
        else
            throw new Error("constants."+key+" does not contain an element with id '"+id+"'");
    };
});

constants.getExpandableFormats = function() {
    return constants.formats.filter(function(format) {
        return format.units.exists(function(unit) { return unit.expandable; });
    });
};

// only do this for constants.json
if (constants.metrics && constants.metrics.length > 0) {
    var parse = require('esprima').parse;

    constants.metrics.filter(function(m) { return m.computed; }).forEach(function(m) {
        m.ast = parse(m.formula).body[0].expression;
    });
}

module.exports = constants;